/**
 * AnimalRescue API
 * API for OSS AnimalRescue
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering */

export class VetsApi {
    protected basePath = 'https://virtserver.swaggerhub.com/jgartee/AnimalRescue/1.0.0';
    public defaultHeaders : any = {};

    static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

    constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
        if (basePath !== undefined) {
            this.basePath = basePath;
        }
    }

    /**
     * adds a Cat with a unique id
     * @summary creates a new Cat
     * @param catToCreate full Cat object with new id
     */
    public createCat (catToCreate?: models.Cat, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: catToCreate,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * creates a new, unique Contact
     * @summary creates new Contact with a unique id
     * @param createContact new Contact object
     */
    public createContact (createContact: models.Contact, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/contact';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'createContact' is not null or undefined
        if (createContact === null || createContact === undefined) {
            throw new Error('Required parameter createContact was null or undefined when calling createContact.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: createContact,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * adds a Dog with a unique id
     * @summary creates a new Dog
     * @param dogToCreate full Dog object with new id
     */
    public createDog (dogToCreate?: models.Dog, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: dogToCreate,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * creates a new, unique Donor
     * @summary creates new Donor with a unique id
     * @param createDonor new Donor object
     */
    public createDonor (createDonor: models.Donor, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/donor';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'createDonor' is not null or undefined
        if (createDonor === null || createDonor === undefined) {
            throw new Error('Required parameter createDonor was null or undefined when calling createDonor.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: createDonor,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * creates a new, unique Foster
     * @summary creates new Foster with a unique id
     * @param createFoster new Foster object
     */
    public createFoster (createFoster: models.Foster, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/foster';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'createFoster' is not null or undefined
        if (createFoster === null || createFoster === undefined) {
            throw new Error('Required parameter createFoster was null or undefined when calling createFoster.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: createFoster,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * creates a new, unique Volunteer
     * @summary creates new Volunteer with a unique id
     * @param createVolunteer new Volunteer object
     */
    public createVolunteer (createVolunteer: models.Volunteer, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/volunteer';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'createVolunteer' is not null or undefined
        if (createVolunteer === null || createVolunteer === undefined) {
            throw new Error('Required parameter createVolunteer was null or undefined when calling createVolunteer.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: createVolunteer,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * deletes a cat
     * @summary deletes an existing Cat by id
     * @param id Specifies the unique id of an existing Cat 
     */
    public deleteCat (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteCat.');
        }

        if (id !== undefined) {
            queryParameters['id'] = id;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Deletes an existing Cat by id
     * @summary retrieves a Cat by id
     * @param id 
     */
    public deleteCatById (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteCatById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * deletes a dog
     * @summary deletes an existing Dog by id
     * @param id Specifies the unique id of an existing Dog 
     */
    public deleteDog (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteDog.');
        }

        if (id !== undefined) {
            queryParameters['id'] = id;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Deletes an existing Dog by id
     * @summary retrieves a Dog by id
     * @param id 
     */
    public deleteDogById (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteDogById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Deletes an existing Location by id
     * @summary retrieves a Location by id
     * @param id 
     */
    public deleteLocationById (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/location/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteLocationById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * used to check on the api status
     * @summary reports whether the API is up and running
     */
    public getApiHealth (extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/health';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Gets an existing Cat by id
     * @summary retrieves a Cat by id
     * @param id 
     */
    public getCatById (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.Cat> {
        const localVarPath = this.basePath + '/cat/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getCatById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Given a state, return an alpha list of counties in that state
     * @summary retrieves counties for the provided state
     * @param state state to retrieve counties for
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public getCountiesByState (state: string, limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<string>> {
        const localVarPath = this.basePath + '/county';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'state' is not null or undefined
        if (state === null || state === undefined) {
            throw new Error('Required parameter state was null or undefined when calling getCountiesByState.');
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (state !== undefined) {
            queryParameters['state'] = state;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Gets an existing Dog by id
     * @summary retrieves a Dog by id
     * @param id 
     */
    public getDogById (id: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.Dog> {
        const localVarPath = this.basePath + '/dog/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getDogById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Returns details about a specific Location 
     * @summary returns a specific location for the Rescue
     * @param id 
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public getLocationById (id: string, limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.Location> {
        const localVarPath = this.basePath + '/location/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getLocationById.');
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * sends a partial JSON Cat structure for an existing Cat id
     * @summary updates a Cat
     * @param updateInfo json object containing specific values to update for an existing Cat id
     */
    public patchCat (updateInfo: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'updateInfo' is not null or undefined
        if (updateInfo === null || updateInfo === undefined) {
            throw new Error('Required parameter updateInfo was null or undefined when calling patchCat.');
        }

        if (updateInfo !== undefined) {
            queryParameters['updateInfo'] = updateInfo;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PATCH',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Cat by id with only elements that are changing
     * @summary updates a Cat by id
     * @param id unique id of Cat to patch
     * @param patchCat partial json object of Cat with fields to patch
     */
    public patchCatById (id: string, patchCat: models.Cat, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling patchCatById.');
        }

        // verify required parameter 'patchCat' is not null or undefined
        if (patchCat === null || patchCat === undefined) {
            throw new Error('Required parameter patchCat was null or undefined when calling patchCatById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PATCH',
            url: localVarPath,
            data: patchCat,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * sends a partial JSON Dog structure for an existing Dog id
     * @summary updates a Dog
     * @param updateInfo json object containing specific values to update for an existing Dog id
     */
    public patchDog (updateInfo: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'updateInfo' is not null or undefined
        if (updateInfo === null || updateInfo === undefined) {
            throw new Error('Required parameter updateInfo was null or undefined when calling patchDog.');
        }

        if (updateInfo !== undefined) {
            queryParameters['updateInfo'] = updateInfo;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PATCH',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Dog by id with only elements that are changing
     * @summary updates a Dog by id
     * @param id unique id of Dog to patch
     * @param patchDog partial json object of Dog with fields to patch
     */
    public patchDogById (id: string, patchDog: models.Dog, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling patchDogById.');
        }

        // verify required parameter 'patchDog' is not null or undefined
        if (patchDog === null || patchDog === undefined) {
            throw new Error('Required parameter patchDog was null or undefined when calling patchDogById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PATCH',
            url: localVarPath,
            data: patchDog,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Location by id with only elements that are changing
     * @summary updates a Location by id
     * @param id unique id of Location to patch
     * @param patchLocation partial json object of Location with fields to patch
     */
    public patchLocationById (id: string, patchLocation: models.Location, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/location/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling patchLocationById.');
        }

        // verify required parameter 'patchLocation' is not null or undefined
        if (patchLocation === null || patchLocation === undefined) {
            throw new Error('Required parameter patchLocation was null or undefined when calling patchLocationById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PATCH',
            url: localVarPath,
            data: patchLocation,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all Buildings at the Rescue 
     * @summary searches all buildings at the Rescue
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     */
    public searchAdoptions (limit?: number, offset?: number, fromDate?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Building>> {
        const localVarPath = this.basePath + '/adoption';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all Buildings at the Rescue 
     * @summary returns all buildings at a Rescue Location
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public searchBuildings (limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Building>> {
        const localVarPath = this.basePath + '/location/building';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all cats currently in the shelter. Allows filters. 
     * @summary searches cats
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     * @param name Specifies a matching pattern for the name
     * @param adoptionStatus Specifies one of the valid AdoptionStatus values
     * @param breed breed of cat to retrieve
     * @param color Specifies one of the valid CatColors
     * @param gender Specifies on of the valid Gender
     */
    public searchCats (limit?: number, offset?: number, fromDate?: string, name?: string, adoptionStatus?: string, breed?: string, color?: string, gender?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Cat>> {
        const localVarPath = this.basePath + '/cat';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        if (name !== undefined) {
            queryParameters['name'] = name;
        }

        if (adoptionStatus !== undefined) {
            queryParameters['adoptionStatus'] = adoptionStatus;
        }

        if (breed !== undefined) {
            queryParameters['breed'] = breed;
        }

        if (color !== undefined) {
            queryParameters['color'] = color;
        }

        if (gender !== undefined) {
            queryParameters['gender'] = gender;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all contacts. Allows filters. 
     * @summary searches contacts
     * @param state state to retrieve counties for
     * @param searchString pass an optional search string for looking up Fosters
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     */
    public searchContacts (state: string, searchString?: string, limit?: number, offset?: number, fromDate?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Contact>> {
        const localVarPath = this.basePath + '/contact';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'state' is not null or undefined
        if (state === null || state === undefined) {
            throw new Error('Required parameter state was null or undefined when calling searchContacts.');
        }

        if (searchString !== undefined) {
            queryParameters['searchString'] = searchString;
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        if (state !== undefined) {
            queryParameters['state'] = state;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all dogss currently in the shelter. Allows filters. 
     * @summary searches dogs
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     * @param name Specifies a matching pattern for the name
     * @param adoptionStatus Specifies one of the valid AdoptionStatus values
     * @param breed breed of dog to retrieve
     * @param color Specifies one of the valid DogColors
     * @param gender Specifies on of the valid Gender
     */
    public searchDobs (limit?: number, offset?: number, fromDate?: string, name?: string, adoptionStatus?: string, breed?: string, color?: string, gender?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Dog>> {
        const localVarPath = this.basePath + '/dog';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        if (name !== undefined) {
            queryParameters['name'] = name;
        }

        if (adoptionStatus !== undefined) {
            queryParameters['adoptionStatus'] = adoptionStatus;
        }

        if (breed !== undefined) {
            queryParameters['breed'] = breed;
        }

        if (color !== undefined) {
            queryParameters['color'] = color;
        }

        if (gender !== undefined) {
            queryParameters['gender'] = gender;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all Donors. Allows filters. 
     * @summary searches animal rescue doners
     * @param state state to retrieve counties for
     * @param searchString pass an optional search string for looking up Fosters
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     */
    public searchDonors (state: string, searchString?: string, limit?: number, offset?: number, fromDate?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Donor>> {
        const localVarPath = this.basePath + '/donor';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'state' is not null or undefined
        if (state === null || state === undefined) {
            throw new Error('Required parameter state was null or undefined when calling searchDonors.');
        }

        if (searchString !== undefined) {
            queryParameters['searchString'] = searchString;
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        if (state !== undefined) {
            queryParameters['state'] = state;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all registered Fosters. Allows filters. 
     * @summary searches animal fosters
     * @param searchString pass an optional search string for looking up Fosters
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     */
    public searchFosters (searchString?: string, limit?: number, offset?: number, fromDate?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Foster>> {
        const localVarPath = this.basePath + '/foster';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (searchString !== undefined) {
            queryParameters['searchString'] = searchString;
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * By passing in the appropriate options, you can search for available inventory in the system 
     * @summary searches inventory
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param searchString pass an optional search string for looking up inventory
     */
    public searchInventory (limit?: number, offset?: number, searchString?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.InventoryItem>> {
        const localVarPath = this.basePath + '/inventory';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (searchString !== undefined) {
            queryParameters['searchString'] = searchString;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all kennels for all locations
     * @summary returns all kennels in a Room
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public searchKennels (limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Kennel>> {
        const localVarPath = this.basePath + '/location/building/room/kennel';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all Locations for the Rescue 
     * @summary searches all locations for the Rescue
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public searchLocations (limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Location>> {
        const localVarPath = this.basePath + '/location';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all Rooms in a Building
     * @summary searches all buildings at the Rescue
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     */
    public searchRoomss (limit?: number, offset?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Room>> {
        const localVarPath = this.basePath + '/location/building/room';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * With no parameters, returns all registered Volunteers. Allows filters. 
     * @summary searches volunteers
     * @param searchString pass an optional search string for looking up Fosters
     * @param limit Limits the number of items on a page
     * @param offset Specifies the page number of the artists to be displayed
     * @param fromDate Specifies the first intake date to return
     */
    public searchVolunteers (searchString?: string, limit?: number, offset?: number, fromDate?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Volunteer>> {
        const localVarPath = this.basePath + '/volunteer';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (searchString !== undefined) {
            queryParameters['searchString'] = searchString;
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (fromDate !== undefined) {
            queryParameters['fromDate'] = fromDate;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * updates a Cat with a unique id
     * @summary updates an existing Cat by id
     * @param catToUpdate full Cat object with id of an existing Cat
     */
    public updateCat (catToUpdate?: models.Cat, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'PUT',
            url: localVarPath,
            data: catToUpdate,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Cat by id
     * @summary updates a Cat by id
     * @param id 
     * @param updateCat unique id of Cat to update
     */
    public updateCatById (id: string, updateCat: models.Cat, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/cat/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateCatById.');
        }

        // verify required parameter 'updateCat' is not null or undefined
        if (updateCat === null || updateCat === undefined) {
            throw new Error('Required parameter updateCat was null or undefined when calling updateCatById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PUT',
            url: localVarPath,
            data: updateCat,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * updates a Dog with a unique id
     * @summary updates an existing Dog by id
     * @param dogToUpdate full Dog object with id of an existing Dog
     */
    public updateDog (dogToUpdate?: models.Dog, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'PUT',
            url: localVarPath,
            data: dogToUpdate,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Dog by id
     * @summary updates a Dog by id
     * @param id 
     * @param updateCat unique id of Dog to update
     */
    public updateDogById (id: string, updateCat: models.Dog, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/dog/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateDogById.');
        }

        // verify required parameter 'updateCat' is not null or undefined
        if (updateCat === null || updateCat === undefined) {
            throw new Error('Required parameter updateCat was null or undefined when calling updateDogById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PUT',
            url: localVarPath,
            data: updateCat,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Updates an existing Location by id
     * @summary updates a Location by id
     * @param id 
     * @param updateCat unique id of Location to update
     */
    public updateLocationById (id: string, updateCat: models.Location, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/location/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateLocationById.');
        }

        // verify required parameter 'updateCat' is not null or undefined
        if (updateCat === null || updateCat === undefined) {
            throw new Error('Required parameter updateCat was null or undefined when calling updateLocationById.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'PUT',
            url: localVarPath,
            data: updateCat,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
}
