/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CountyMI } from './countyMI';
import { NoteId } from './noteId';


export interface Address {
    addressLine1?: string;
    addressLine2?: string;
    city: string;
    stateOrProvence: string;
    county?: CountyMI;
    country?: string;
    notes?: Array<NoteId>;
}
