/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type AdoptionStatus = 'Adoption Pending' | 'Available' | 'Available Pending Spay/Neuter' | 'Medical Hold' | 'Pending Intake Testing';

export const AdoptionStatus = {
    AdoptionPending: 'Adoption Pending' as AdoptionStatus,
    Available: 'Available' as AdoptionStatus,
    AvailablePendingSpayNeuter: 'Available Pending Spay/Neuter' as AdoptionStatus,
    MedicalHold: 'Medical Hold' as AdoptionStatus,
    PendingIntakeTesting: 'Pending Intake Testing' as AdoptionStatus
}
