/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type AnimalType = 'Cat' | 'Dog';

export const AnimalType = {
    Cat: 'Cat' as AnimalType,
    Dog: 'Dog' as AnimalType
}
