/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BuildingId } from './buildingId';
import { KennelId } from './kennelId';
import { NoteId } from './noteId';
import { RoomId } from './roomId';


export interface Building {
    id: BuildingId;
    name?: string;
    rooms?: Array<RoomId>;
    kennels?: Array<KennelId>;
    notes?: Array<NoteId>;
}
