/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnimalInfo } from './animalInfo';
import { CatInfo } from './catInfo';


export interface Cat {
    animal: AnimalInfo;
    cat: CatInfo;
}
