/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type CatBreeds = 'Undetermined' | 'Abyssinian' | 'American Curl' | 'Bengal' | 'Domestic Longhair' | 'Domestic Mediumhair' | 'Domestic Shorthair' | 'Fold' | 'Himalayan' | 'Maine Coon' | 'Manx' | 'Persian' | 'RagaMuffin' | 'Ragdoll' | 'Russian Blue' | 'Siamese' | 'Snowshoe' | 'Sphynx';

export const CatBreeds = {
    Undetermined: 'Undetermined' as CatBreeds,
    Abyssinian: 'Abyssinian' as CatBreeds,
    AmericanCurl: 'American Curl' as CatBreeds,
    Bengal: 'Bengal' as CatBreeds,
    DomesticLonghair: 'Domestic Longhair' as CatBreeds,
    DomesticMediumhair: 'Domestic Mediumhair' as CatBreeds,
    DomesticShorthair: 'Domestic Shorthair' as CatBreeds,
    Fold: 'Fold' as CatBreeds,
    Himalayan: 'Himalayan' as CatBreeds,
    MaineCoon: 'Maine Coon' as CatBreeds,
    Manx: 'Manx' as CatBreeds,
    Persian: 'Persian' as CatBreeds,
    RagaMuffin: 'RagaMuffin' as CatBreeds,
    Ragdoll: 'Ragdoll' as CatBreeds,
    RussianBlue: 'Russian Blue' as CatBreeds,
    Siamese: 'Siamese' as CatBreeds,
    Snowshoe: 'Snowshoe' as CatBreeds,
    Sphynx: 'Sphynx' as CatBreeds
}
