/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type CatColors = 'White' | 'Black' | 'Black and White' | 'Brown' | 'Brown Tabby' | 'Brown and White' | 'Buff' | 'Buff and White' | 'Buff Tabby' | 'Calico' | 'Dilute Calico' | 'Flame Point' | 'Gray' | 'Gray and White' | 'Gray Tabby' | 'Lavendar/Lilac Point' | 'Orange Tabby' | 'Orange and White' | 'Seal Point' | 'Silver' | 'Silver and White' | 'Silver Tabby' | 'Snowshoe' | 'Tortie';

export const CatColors = {
    White: 'White' as CatColors,
    Black: 'Black' as CatColors,
    BlackAndWhite: 'Black and White' as CatColors,
    Brown: 'Brown' as CatColors,
    BrownTabby: 'Brown Tabby' as CatColors,
    BrownAndWhite: 'Brown and White' as CatColors,
    Buff: 'Buff' as CatColors,
    BuffAndWhite: 'Buff and White' as CatColors,
    BuffTabby: 'Buff Tabby' as CatColors,
    Calico: 'Calico' as CatColors,
    DiluteCalico: 'Dilute Calico' as CatColors,
    FlamePoint: 'Flame Point' as CatColors,
    Gray: 'Gray' as CatColors,
    GrayAndWhite: 'Gray and White' as CatColors,
    GrayTabby: 'Gray Tabby' as CatColors,
    LavendarLilacPoint: 'Lavendar/Lilac Point' as CatColors,
    OrangeTabby: 'Orange Tabby' as CatColors,
    OrangeAndWhite: 'Orange and White' as CatColors,
    SealPoint: 'Seal Point' as CatColors,
    Silver: 'Silver' as CatColors,
    SilverAndWhite: 'Silver and White' as CatColors,
    SilverTabby: 'Silver Tabby' as CatColors,
    Snowshoe: 'Snowshoe' as CatColors,
    Tortie: 'Tortie' as CatColors
}
