/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
import { ContactId } from './contactId';
import { EmailAddress } from './emailAddress';
import { NoteId } from './noteId';
import { PhoneNumber } from './phoneNumber';


export interface Contact {
    id?: ContactId;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    addresses?: Array<Address>;
    phones?: Array<PhoneNumber>;
    emails?: Array<EmailAddress>;
    dateOfBirth?: string;
    driversLicense?: string;
    notes?: Array<NoteId>;
}
