/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DayOfMonthSelect } from './dayOfMonthSelect';
import { MonthSelect } from './monthSelect';
import { YearSelect } from './yearSelect';


export interface DateRange {
    startYear?: YearSelect;
    startMonth?: MonthSelect;
    startDayOfMonth?: DayOfMonthSelect;
    endYear?: YearSelect;
    endMonth?: MonthSelect;
    endDayOfMonth?: DayOfMonthSelect;
}
