/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type DayOfWeekSelect = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';

export const DayOfWeekSelect = {
    Monday: 'Monday' as DayOfWeekSelect,
    Tuesday: 'Tuesday' as DayOfWeekSelect,
    Wednesday: 'Wednesday' as DayOfWeekSelect,
    Thursday: 'Thursday' as DayOfWeekSelect,
    Friday: 'Friday' as DayOfWeekSelect,
    Saturday: 'Saturday' as DayOfWeekSelect,
    Sunday: 'Sunday' as DayOfWeekSelect
}
