/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type DayOfMonthSelect = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31;

export const DayOfMonthSelect = {
    NUMBER_1: 1 as DayOfMonthSelect,
    NUMBER_2: 2 as DayOfMonthSelect,
    NUMBER_3: 3 as DayOfMonthSelect,
    NUMBER_4: 4 as DayOfMonthSelect,
    NUMBER_5: 5 as DayOfMonthSelect,
    NUMBER_6: 6 as DayOfMonthSelect,
    NUMBER_7: 7 as DayOfMonthSelect,
    NUMBER_8: 8 as DayOfMonthSelect,
    NUMBER_9: 9 as DayOfMonthSelect,
    NUMBER_10: 10 as DayOfMonthSelect,
    NUMBER_11: 11 as DayOfMonthSelect,
    NUMBER_12: 12 as DayOfMonthSelect,
    NUMBER_13: 13 as DayOfMonthSelect,
    NUMBER_14: 14 as DayOfMonthSelect,
    NUMBER_15: 15 as DayOfMonthSelect,
    NUMBER_16: 16 as DayOfMonthSelect,
    NUMBER_17: 17 as DayOfMonthSelect,
    NUMBER_18: 18 as DayOfMonthSelect,
    NUMBER_19: 19 as DayOfMonthSelect,
    NUMBER_20: 20 as DayOfMonthSelect,
    NUMBER_21: 21 as DayOfMonthSelect,
    NUMBER_22: 22 as DayOfMonthSelect,
    NUMBER_23: 23 as DayOfMonthSelect,
    NUMBER_24: 24 as DayOfMonthSelect,
    NUMBER_25: 25 as DayOfMonthSelect,
    NUMBER_26: 26 as DayOfMonthSelect,
    NUMBER_27: 27 as DayOfMonthSelect,
    NUMBER_28: 28 as DayOfMonthSelect,
    NUMBER_29: 29 as DayOfMonthSelect,
    NUMBER_30: 30 as DayOfMonthSelect,
    NUMBER_31: 31 as DayOfMonthSelect
}
