/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type DogBreeds = 'Undetermined' | 'Akita' | 'American Bulldog' | 'American Eskimo Dog' | 'Australian Cattle Dog' | 'Australian Shepherd' | 'Basenji' | 'Basset Hound' | 'Beagle' | 'Bernese Mountain Dog' | 'Bichon Frise' | 'Bloodhound' | 'Border Collie' | 'Boston Terrier' | 'Boxer Scottish' | 'Brittany Spaniel' | 'Bull Terrier' | 'Bulldog' | 'Bullmastiff' | 'Catahoula Leopard Dog' | 'Cavalier King Charles Spaniel' | 'Chihuahua' | 'Chinese Crested' | 'Chow Chow' | 'Cockapoo' | 'Cocker Spaniel' | 'Collie' | 'Dalmatian' | 'Dashshund' | 'Doberman Pinscher' | 'English Setter' | 'Flat-Coated Retriever' | 'Fox Terrier' | 'French Bulldog' | 'German Shepherd' | 'German Shorthaired Pointer' | 'Golden Retriever' | 'Goldendoodle' | 'Great Dane' | 'Great Pyrenees' | 'Greyhound' | 'Havanese' | 'Irish Setter' | 'Jack Russell Terrier' | 'Labradoodle';

export const DogBreeds = {
    Undetermined: 'Undetermined' as DogBreeds,
    Akita: 'Akita' as DogBreeds,
    AmericanBulldog: 'American Bulldog' as DogBreeds,
    AmericanEskimoDog: 'American Eskimo Dog' as DogBreeds,
    AustralianCattleDog: 'Australian Cattle Dog' as DogBreeds,
    AustralianShepherd: 'Australian Shepherd' as DogBreeds,
    Basenji: 'Basenji' as DogBreeds,
    BassetHound: 'Basset Hound' as DogBreeds,
    Beagle: 'Beagle' as DogBreeds,
    BerneseMountainDog: 'Bernese Mountain Dog' as DogBreeds,
    BichonFrise: 'Bichon Frise' as DogBreeds,
    Bloodhound: 'Bloodhound' as DogBreeds,
    BorderCollie: 'Border Collie' as DogBreeds,
    BostonTerrier: 'Boston Terrier' as DogBreeds,
    BoxerScottish: 'Boxer Scottish' as DogBreeds,
    BrittanySpaniel: 'Brittany Spaniel' as DogBreeds,
    BullTerrier: 'Bull Terrier' as DogBreeds,
    Bulldog: 'Bulldog' as DogBreeds,
    Bullmastiff: 'Bullmastiff' as DogBreeds,
    CatahoulaLeopardDog: 'Catahoula Leopard Dog' as DogBreeds,
    CavalierKingCharlesSpaniel: 'Cavalier King Charles Spaniel' as DogBreeds,
    Chihuahua: 'Chihuahua' as DogBreeds,
    ChineseCrested: 'Chinese Crested' as DogBreeds,
    ChowChow: 'Chow Chow' as DogBreeds,
    Cockapoo: 'Cockapoo' as DogBreeds,
    CockerSpaniel: 'Cocker Spaniel' as DogBreeds,
    Collie: 'Collie' as DogBreeds,
    Dalmatian: 'Dalmatian' as DogBreeds,
    Dashshund: 'Dashshund' as DogBreeds,
    DobermanPinscher: 'Doberman Pinscher' as DogBreeds,
    EnglishSetter: 'English Setter' as DogBreeds,
    FlatCoatedRetriever: 'Flat-Coated Retriever' as DogBreeds,
    FoxTerrier: 'Fox Terrier' as DogBreeds,
    FrenchBulldog: 'French Bulldog' as DogBreeds,
    GermanShepherd: 'German Shepherd' as DogBreeds,
    GermanShorthairedPointer: 'German Shorthaired Pointer' as DogBreeds,
    GoldenRetriever: 'Golden Retriever' as DogBreeds,
    Goldendoodle: 'Goldendoodle' as DogBreeds,
    GreatDane: 'Great Dane' as DogBreeds,
    GreatPyrenees: 'Great Pyrenees' as DogBreeds,
    Greyhound: 'Greyhound' as DogBreeds,
    Havanese: 'Havanese' as DogBreeds,
    IrishSetter: 'Irish Setter' as DogBreeds,
    JackRussellTerrier: 'Jack Russell Terrier' as DogBreeds,
    Labradoodle: 'Labradoodle' as DogBreeds
}
