/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type DogColors = 'Black' | 'Black and White' | 'White' | 'Brindle' | 'Tri-Color' | 'Brown' | 'Brown and White' | 'Gray/Blue' | 'Gray and White' | 'Red/Cinnamon' | 'Black and Tan' | 'Tan' | 'Tan and White';

export const DogColors = {
    Black: 'Black' as DogColors,
    BlackAndWhite: 'Black and White' as DogColors,
    White: 'White' as DogColors,
    Brindle: 'Brindle' as DogColors,
    TriColor: 'Tri-Color' as DogColors,
    Brown: 'Brown' as DogColors,
    BrownAndWhite: 'Brown and White' as DogColors,
    GrayBlue: 'Gray/Blue' as DogColors,
    GrayAndWhite: 'Gray and White' as DogColors,
    RedCinnamon: 'Red/Cinnamon' as DogColors,
    BlackAndTan: 'Black and Tan' as DogColors,
    Tan: 'Tan' as DogColors,
    TanAndWhite: 'Tan and White' as DogColors
}
