/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContactId } from './contactId';
import { DoNotAdoptId } from './doNotAdoptId';
import { NoteId } from './noteId';


/**
 * Entity representing an individual who is not eligible to adopt from the Rescue
 */
export interface DoNotAdoptEntry {
    id?: DoNotAdoptId;
    timestamp?: string;
    contact?: ContactId;
    notes?: Array<NoteId>;
}
