/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type EmailType = 'Primary' | 'Secondary';

export const EmailType = {
    Primary: 'Primary' as EmailType,
    Secondary: 'Secondary' as EmailType
}
