/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EmailType } from './emailType';
import { NoteId } from './noteId';


export interface EmailAddress {
    email: string;
    emailType: EmailType;
    notes?: Array<NoteId>;
}
