/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type Gender = 'Male' | 'Female' | 'Undetermined';

export const Gender = {
    Male: 'Male' as Gender,
    Female: 'Female' as Gender,
    Undetermined: 'Undetermined' as Gender
}
