/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type HalfHourMilitaryTimeSelect = '00:00' | '00:30' | '01:00' | '01:30' | '02:00' | '02:30' | '03:00' | '03:30' | '04:00' | '04:30' | '05:00' | '05:30' | '06:00' | '06:30' | '07:00' | '07:30' | '08:00' | '08:30' | '09:00' | '09:30' | '10:00' | '10:30' | '11:00' | '11:30' | '12:00' | '12:30' | '13:00' | '13:30' | '14:00' | '14:30' | '15:00' | '15:30' | '16:00' | '16:30' | '17:00' | '17:30' | '18:00' | '18:30' | '19:00' | '19:30' | '20:00' | '20:30' | '21:00' | '21:30' | '22:00' | '22:30' | '23:00' | '23:30';

export const HalfHourMilitaryTimeSelect = {
    _0000: '00:00' as HalfHourMilitaryTimeSelect,
    _0030: '00:30' as HalfHourMilitaryTimeSelect,
    _0100: '01:00' as HalfHourMilitaryTimeSelect,
    _0130: '01:30' as HalfHourMilitaryTimeSelect,
    _0200: '02:00' as HalfHourMilitaryTimeSelect,
    _0230: '02:30' as HalfHourMilitaryTimeSelect,
    _0300: '03:00' as HalfHourMilitaryTimeSelect,
    _0330: '03:30' as HalfHourMilitaryTimeSelect,
    _0400: '04:00' as HalfHourMilitaryTimeSelect,
    _0430: '04:30' as HalfHourMilitaryTimeSelect,
    _0500: '05:00' as HalfHourMilitaryTimeSelect,
    _0530: '05:30' as HalfHourMilitaryTimeSelect,
    _0600: '06:00' as HalfHourMilitaryTimeSelect,
    _0630: '06:30' as HalfHourMilitaryTimeSelect,
    _0700: '07:00' as HalfHourMilitaryTimeSelect,
    _0730: '07:30' as HalfHourMilitaryTimeSelect,
    _0800: '08:00' as HalfHourMilitaryTimeSelect,
    _0830: '08:30' as HalfHourMilitaryTimeSelect,
    _0900: '09:00' as HalfHourMilitaryTimeSelect,
    _0930: '09:30' as HalfHourMilitaryTimeSelect,
    _1000: '10:00' as HalfHourMilitaryTimeSelect,
    _1030: '10:30' as HalfHourMilitaryTimeSelect,
    _1100: '11:00' as HalfHourMilitaryTimeSelect,
    _1130: '11:30' as HalfHourMilitaryTimeSelect,
    _1200: '12:00' as HalfHourMilitaryTimeSelect,
    _1230: '12:30' as HalfHourMilitaryTimeSelect,
    _1300: '13:00' as HalfHourMilitaryTimeSelect,
    _1330: '13:30' as HalfHourMilitaryTimeSelect,
    _1400: '14:00' as HalfHourMilitaryTimeSelect,
    _1430: '14:30' as HalfHourMilitaryTimeSelect,
    _1500: '15:00' as HalfHourMilitaryTimeSelect,
    _1530: '15:30' as HalfHourMilitaryTimeSelect,
    _1600: '16:00' as HalfHourMilitaryTimeSelect,
    _1630: '16:30' as HalfHourMilitaryTimeSelect,
    _1700: '17:00' as HalfHourMilitaryTimeSelect,
    _1730: '17:30' as HalfHourMilitaryTimeSelect,
    _1800: '18:00' as HalfHourMilitaryTimeSelect,
    _1830: '18:30' as HalfHourMilitaryTimeSelect,
    _1900: '19:00' as HalfHourMilitaryTimeSelect,
    _1930: '19:30' as HalfHourMilitaryTimeSelect,
    _2000: '20:00' as HalfHourMilitaryTimeSelect,
    _2030: '20:30' as HalfHourMilitaryTimeSelect,
    _2100: '21:00' as HalfHourMilitaryTimeSelect,
    _2130: '21:30' as HalfHourMilitaryTimeSelect,
    _2200: '22:00' as HalfHourMilitaryTimeSelect,
    _2230: '22:30' as HalfHourMilitaryTimeSelect,
    _2300: '23:00' as HalfHourMilitaryTimeSelect,
    _2330: '23:30' as HalfHourMilitaryTimeSelect
}
