/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnimalId } from './animalId';
import { ContactId } from './contactId';
import { IntakeId } from './intakeId';
import { IntakeType } from './intakeType';
import { NoteId } from './noteId';
import { OrganizationId } from './organizationId';
import { ParNumber } from './parNumber';


/**
 * Aggregate representing an animal being registered into the Rescue
 */
export interface Intake {
    id: IntakeId;
    parNumber: ParNumber;
    animalInfoId?: AnimalId;
    dateOfIntake: string;
    typeOfIntake: IntakeType;
    surrendingPartyId?: ContactId;
    transferringShelterId?: OrganizationId;
    placeInIsolation: boolean;
    staffId?: ContactId;
    notes?: Array<NoteId>;
}
