/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * List of allowable Intake types describing how an animal came to the Rescue
 */
export type IntakeType = 'Owner Surrender' | 'Failed Adoption' | 'Stray Surrender' | 'Abandonded at Rescue' | 'Shelter Transfer';

export const IntakeType = {
    OwnerSurrender: 'Owner Surrender' as IntakeType,
    FailedAdoption: 'Failed Adoption' as IntakeType,
    StraySurrender: 'Stray Surrender' as IntakeType,
    AbandondedAtRescue: 'Abandonded at Rescue' as IntakeType,
    ShelterTransfer: 'Shelter Transfer' as IntakeType
}
