/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonPointer } from './jsonPointer';


export interface JsonPatchInner {
    op: JsonPatchInner.OpEnum;
    path: JsonPointer;
    from?: JsonPointer;
    value?: any;
}
export namespace JsonPatchInner {
    export type OpEnum = 'add' | 'remove' | 'copy' | 'move' | 'delete' | 'replace' | 'test';
    export const OpEnum = {
        Add: 'add' as OpEnum,
        Remove: 'remove' as OpEnum,
        Copy: 'copy' as OpEnum,
        Move: 'move' as OpEnum,
        Delete: 'delete' as OpEnum,
        Replace: 'replace' as OpEnum,
        Test: 'test' as OpEnum
    }
}
