/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonPointer } from './jsonPointer';


/**
 * copy operation. \"from\" is a JSON Pointer.
 */
export interface JsonPatchCopy {
    op: JsonPatchCopy.OpEnum;
    from: JsonPointer;
}
export namespace JsonPatchCopy {
    export type OpEnum = 'copy';
    export const OpEnum = {
        Copy: 'copy' as OpEnum
    }
}
