/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonPointer } from './jsonPointer';


/**
 * test operation. Value can be any JSON value.
 */
export interface JsonPatchTest {
    op: JsonPatchTest.OpEnum;
    path: JsonPointer;
}
export namespace JsonPatchTest {
    export type OpEnum = 'test';
    export const OpEnum = {
        Test: 'test' as OpEnum
    }
}
