/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonPatchInner } from './jsonPatchInner';


/**
 * Given the limitations of the Swagger 2.0 specification, this structure acts as a compromise that provides all fields required for any of the enumerated patch types.  They will be used as defined in RFC 6920.  In many cases, some of the fields will be unused.  It is the responsibility of the API service to access and process only those properties that are appropriate for the operation type specified. These are the fields used by each of the enumerated values - add/path/value, remove/path, copy/fromPath/path, move/fromPath/path, delete/path, replace/path/value, test/path/value.
 */
export interface JsonPatch extends Array<JsonPatchInner> {
}
