/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DefinitionsJsonPointer } from './definitionsJsonPointer';


/**
 * replace operation. Value can be any JSON value.
 */
export interface JsonPatchReplace {
    op: JsonPatchReplace.OpEnum;
    path: DefinitionsJsonPointer;
}
export namespace JsonPatchReplace {
    export type OpEnum = 'replace';
    export const OpEnum = {
        Replace: 'replace' as OpEnum
    }
}
