/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonPointer } from './jsonPointer';


/**
 * remove operation. Only a path is specified.
 */
export interface JsonPatchRemove {
    op: JsonPatchRemove.OpEnum;
    path: JsonPointer;
}
export namespace JsonPatchRemove {
    export type OpEnum = 'remove';
    export const OpEnum = {
        Remove: 'remove' as OpEnum
    }
}
