/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnimalId } from './animalId';
import { KennelId } from './kennelId';
import { NoteId } from './noteId';
import { Species } from './species';


export interface Kennel {
    id: KennelId;
    name?: string;
    species?: Species;
    maxOccupancy: number;
    animals?: Array<AnimalId>;
    notes?: Array<NoteId>;
}
