/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnimalId } from './animalId';
import { AnimalType } from './animalType';
import { KennelId } from './kennelId';
import { NoteId } from './noteId';


export interface Kennel {
    id: KennelId;
    name?: string;
    species?: AnimalType;
    maxOccupancy: number;
    animals?: Array<AnimalId>;
    notes?: Array<NoteId>;
}
