/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnimalId } from './animalId';
import { LitterId } from './litterId';
import { NoteId } from './noteId';


export interface Litter {
    id: LitterId;
    isMotherIncluded: boolean;
    mother?: AnimalId;
    littermates: Array<AnimalId>;
    notes?: Array<NoteId>;
}
