/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
import { BuildingId } from './buildingId';
import { EnclosureId } from './enclosureId';
import { KennelId } from './kennelId';
import { LocationId } from './locationId';
import { NoteId } from './noteId';


export interface Location {
    id: LocationId;
    name?: string;
    address: Address;
    buildings?: Array<BuildingId>;
    enclosures?: Array<EnclosureId>;
    kennels?: Array<KennelId>;
    notes?: Array<NoteId>;
}
