/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContactId } from './contactId';
import { MedicalEventId } from './medicalEventId';
import { MedicalEventSupportingData } from './medicalEventSupportingData';
import { MedicalEventType } from './medicalEventType';
import { NoteId } from './noteId';


export interface MedicalEvent {
    id: MedicalEventId;
    timestamp: Date;
    type: MedicalEventType;
    supportingData: MedicalEventSupportingData;
    notes?: Array<NoteId>;
    createdBy: ContactId;
}
