/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type MedicalEventType = 'Placed in Isolation' | 'Removed from Isolation' | 'Preventative' | 'Vaccination' | 'Surgery';

export const MedicalEventType = {
    PlacedInIsolation: 'Placed in Isolation' as MedicalEventType,
    RemovedFromIsolation: 'Removed from Isolation' as MedicalEventType,
    Preventative: 'Preventative' as MedicalEventType,
    Vaccination: 'Vaccination' as MedicalEventType,
    Surgery: 'Surgery' as MedicalEventType
}
