/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContactId } from './contactId';
import { MedicalEventId } from './medicalEventId';
import { MedicalEventType } from './medicalEventType';
import { NoteId } from './noteId';
import { SupportingMedicalDataId } from './supportingMedicalDataId';


export interface MedicalEvent {
    id: MedicalEventId;
    timestamp: Date;
    type: MedicalEventType;
    supportingData: SupportingMedicalDataId;
    notes?: Array<NoteId>;
    createdBy: ContactId;
}
