/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type MonthSelect = 'January' | 'February' | 'March' | 'April' | 'May' | 'June' | 'July' | 'August' | 'September' | 'October' | 'November' | 'December';

export const MonthSelect = {
    January: 'January' as MonthSelect,
    February: 'February' as MonthSelect,
    March: 'March' as MonthSelect,
    April: 'April' as MonthSelect,
    May: 'May' as MonthSelect,
    June: 'June' as MonthSelect,
    July: 'July' as MonthSelect,
    August: 'August' as MonthSelect,
    September: 'September' as MonthSelect,
    October: 'October' as MonthSelect,
    November: 'November' as MonthSelect,
    December: 'December' as MonthSelect
}
