/**
 * Animal Rescue API
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NoteId } from './noteId';
import { PhoneNumberPurpose } from './phoneNumberPurpose';
import { PhoneNumberType } from './phoneNumberType';


export interface PhoneNumber {
    number: number;
    phoneType?: PhoneNumberType;
    phonePurpose?: PhoneNumberPurpose;
    noteId?: NoteId;
}
