/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type YearSelect = 2000 | 2001 | 2002 | 2003 | 2004 | 2005 | 2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 | 2026 | 2027 | 2028 | 2029 | 2030 | 2031 | 2032 | 2033 | 2034 | 2035 | 2036 | 2037 | 2038 | 2039 | 2040 | 2041 | 2042 | 2043 | 2044 | 2045 | 2046 | 2047 | 2048 | 2049;

export const YearSelect = {
    NUMBER_2000: 2000 as YearSelect,
    NUMBER_2001: 2001 as YearSelect,
    NUMBER_2002: 2002 as YearSelect,
    NUMBER_2003: 2003 as YearSelect,
    NUMBER_2004: 2004 as YearSelect,
    NUMBER_2005: 2005 as YearSelect,
    NUMBER_2006: 2006 as YearSelect,
    NUMBER_2007: 2007 as YearSelect,
    NUMBER_2008: 2008 as YearSelect,
    NUMBER_2009: 2009 as YearSelect,
    NUMBER_2010: 2010 as YearSelect,
    NUMBER_2011: 2011 as YearSelect,
    NUMBER_2012: 2012 as YearSelect,
    NUMBER_2013: 2013 as YearSelect,
    NUMBER_2014: 2014 as YearSelect,
    NUMBER_2015: 2015 as YearSelect,
    NUMBER_2016: 2016 as YearSelect,
    NUMBER_2017: 2017 as YearSelect,
    NUMBER_2018: 2018 as YearSelect,
    NUMBER_2019: 2019 as YearSelect,
    NUMBER_2020: 2020 as YearSelect,
    NUMBER_2021: 2021 as YearSelect,
    NUMBER_2022: 2022 as YearSelect,
    NUMBER_2023: 2023 as YearSelect,
    NUMBER_2024: 2024 as YearSelect,
    NUMBER_2025: 2025 as YearSelect,
    NUMBER_2026: 2026 as YearSelect,
    NUMBER_2027: 2027 as YearSelect,
    NUMBER_2028: 2028 as YearSelect,
    NUMBER_2029: 2029 as YearSelect,
    NUMBER_2030: 2030 as YearSelect,
    NUMBER_2031: 2031 as YearSelect,
    NUMBER_2032: 2032 as YearSelect,
    NUMBER_2033: 2033 as YearSelect,
    NUMBER_2034: 2034 as YearSelect,
    NUMBER_2035: 2035 as YearSelect,
    NUMBER_2036: 2036 as YearSelect,
    NUMBER_2037: 2037 as YearSelect,
    NUMBER_2038: 2038 as YearSelect,
    NUMBER_2039: 2039 as YearSelect,
    NUMBER_2040: 2040 as YearSelect,
    NUMBER_2041: 2041 as YearSelect,
    NUMBER_2042: 2042 as YearSelect,
    NUMBER_2043: 2043 as YearSelect,
    NUMBER_2044: 2044 as YearSelect,
    NUMBER_2045: 2045 as YearSelect,
    NUMBER_2046: 2046 as YearSelect,
    NUMBER_2047: 2047 as YearSelect,
    NUMBER_2048: 2048 as YearSelect,
    NUMBER_2049: 2049 as YearSelect
}
